.TH "ihm_context" 3 "Thu Jun 6 2013" "Version 1.0" "CS219 - Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ihm_context \- 
.PP
initilise tout globale et static\&. c'est le contexte graphique et evenemenciel\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
initilise tout globale et static\&. c'est le contexte graphique et evenemenciel\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS219 - Sokoban from the source code\&.
