.TH "log_actions_t" 3 "Thu Jun 6 2013" "Version 1.0" "CS219 - Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log_actions_t \- 
.PP
Maillon\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBlog_actions_t\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBlog_actions_t\fP * \fBprevious\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Maillon\&. 
.SH "Field Documentation"
.PP 
.SS "void* data"
donne definissant un coup, a definir avec gab 
.SS "struct \fBlog_actions_t\fP* next"
Le coup suivant 
.SS "struct \fBlog_actions_t\fP* previous"
Le coup precedent 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS219 - Sokoban from the source code\&.
