.TH "static" 3 "Thu Jun 6 2013" "Version 1.0" "CS219 - Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
static \- 
.PP
Contient l'instance du fichier level\&.lvl ainsi que le nombre de niveau Cette variable est globale parce que toutes les fonctions de ce fichier ont besoin de ces informations\&. Cette variable est static pour la proteger car elle est globale\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contient l'instance du fichier level\&.lvl ainsi que le nombre de niveau Cette variable est globale parce que toutes les fonctions de ce fichier ont besoin de ces informations\&. Cette variable est static pour la proteger car elle est globale\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS219 - Sokoban from the source code\&.
