.TH "A:/GitHub/CS219.sokoban/code/testsUnitaires.h" 3 "Thu Jun 6 2013" "Version 1.0" "CS219 - Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A:/GitHub/CS219.sokoban/code/testsUnitaires.h \- 
.PP
Mini-projet CS219 Sokoban\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtest_log_create\fP ()"
.br
.ti -1c
.RI "int \fBtest_log_destroy\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_next\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_previous\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_start\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_end\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_insertAfter\fP (\fBlog_t\fP *, void *)"
.br
.ti -1c
.RI "int \fBtest_log_insertBefore\fP (\fBlog_t\fP *, void *)"
.br
.ti -1c
.RI "int \fBtest_log_freeSelected\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_freeForward\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_freeBackward\fP (\fBlog_t\fP *)"
.br
.ti -1c
.RI "int \fBtest_log_freeAll\fP (\fBlog_t\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Mini-projet CS219 Sokoban\&. 

\fBAuthor:\fP
.RS 4
EYMARD Gabrielle - SCHLOTTERBECK Guillaume 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
04/06/2013 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CS219 - Sokoban from the source code\&.
