.TH "visu_t" 3 "Thu Jun 6 2013" "Version 1.0" "CS219 - Sokoban" \" -*- nroff -*-
.ad l
.nh
.SH NAME
visu_t \- 
.PP
la visu a afficher  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IHM\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ALLEGRO_COLOR \fBcolor\fP"
.br
.ti -1c
.RI "ihm_size \fBsize\fP"
.br
.ti -1c
.RI "char * \fBtxt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
la visu a afficher 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS219 - Sokoban from the source code\&.
